# np.append


In [ ]:
# vstack
concatenate([atleast_2d(_m) for _m in tup], 0)
# i.e. turn all inputs in to 2d (or more) and concatenate on first

# hstack
concatenate([atleast_1d(_m) for _m in tup], axis=<0 or 1>)

# colstack
transform arrays with (if needed)
    array(arr, copy=False, subok=True, ndmin=2).T

# append
concatenate((asarray(arr), values), axis=axis)

# vstack


In [16]:
import numpy as np

a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6]])
c = np.concatenate((a, b), axis=0)
c

array([[1, 2],
       [3, 4],
       [5, 6]])

In [14]:
np.concatenate((c, np.array([7,8,9]).reshape(3,1)), axis=1)

array([[1, 2, 7],
       [3, 4, 8],
       [5, 6, 9]])

In [15]:
np.append(c,  np.array([7,8,9]).reshape(3,1), axis=1)

array([[1, 2, 7],
       [3, 4, 8],
       [5, 6, 9]])